[instrument]
plugin = "https://www.modartt.com/lv2/Pianoteq9"
#plugin = "lv2:http://tytel.org/helm"
#preset = "COA Crispy Pad Organ"

[instrument.params]
"reverb_on" = 1.0
"reverb_dry_wet" = 0.3

[[effect]]
plugin = "lv2:http://calf.sourceforge.net/plugins/Reverb"
preset = "Large Empty Hall"
mix = 0.5

[effect.params]
"Wet Amount" = 0.4

[[effect]]
plugin = "lv2:urn:ardour:a-comp#stereo"
preset = "VocalLeveller"
mix = 1.0

[effect.params]
"Makeup" = 6.0
